apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gpznlw2po-go 
  janus-idp.io/tekton: gpznlw2po-go
  backstage.io/kubernetes-id: gpznlw2po-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gpznlw2po-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml