apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gpznlw2po-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gpznlw2po-go 
  name: gpznlw2po-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gpznlw2po-go 
